<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="search-mobile hidden-dt">
    <form class="form minisearch" id="search_mobile_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
        <div class="field search">
            <div class="control">
                <input id="footer_search"
                        data-mage-init='{"quickSearch":{
                            "formSelector":"#search_mobile_form",
                            "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                            "destinationSelector":"#footer_search_autocomplete"}
                        }'
                        type="text"
                        name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                        value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                        placeholder="<?php /* @escapeNotVerified */ echo __('Search'); ?>"
                        class="input-text"
                        maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                        role="combobox"
                        aria-haspopup="false"
                        aria-autocomplete="both"
                        autocomplete="off"/>
                <?php echo $block->getChildHtml() ?>
            </div>
        </div>
        <div class="actions">
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Search')) ?>"
                    class="action search">
                <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
            </button>
        </div>
    </form>
</div>
