<?php  /* @var \WeltPixel\OwlCarouselSlider\Block\Slider\Custom $this */ ?>

<?php $sliderConfig  = $this->getSliderConfiguration(); ?>
<?php $sliderGeneral = $sliderConfig['slider_config']; ?>
<?php $enabled       = (array_key_exists('status', $sliderGeneral) && $sliderGeneral['status'] !=0) ? true : false; ?>
<?php $type = 'banner-slider'; ?>

<?php if ($enabled) : ?>

    <?php
    $sliderId     = $this->getData('slider_id');
    $breakpoint   = $this->getBreakpointConfiguration();
    $breakpointConfig = json_encode($breakpoint);
    $bannerConfig = $sliderConfig['banner_config'];
    $sliderConfig = json_encode($sliderGeneral);
    $mediaUrl     = $this->getMediaUrl();
    ?>
    
    <?php if($sliderGeneral['show_title']) : ?>
        <div class="content-heading">
            <h2 class="title"><?php echo $sliderGeneral['title']; ?></h2>
        </div>
    <?php endif; ?>

    <div class="custom-slider">
        <div id="slick-slider-<?php echo $sliderId;?>"
            data-mage-init='{"rwSlider" : {
                "type": "<?php echo $type ?>",
                "sliderConfig": <?php echo $sliderConfig ?>,
                "breakpoints": <?php echo $breakpointConfig ?>
            }}'>
            <?php foreach($bannerConfig as $banner) : ?>
                <?php
                    $title = (array_key_exists('title', $banner) && $banner['title'] !='') ? $banner['title'] : false;
                    $showTitle = array_key_exists('show_title', $banner) ? $banner['show_title'] : false;
                    $description = (array_key_exists('description', $banner) && $banner['description'] !='')
                        ? $banner['description'] : false;
                    $showDescription = array_key_exists('show_description', $banner)
                        ? $banner['show_description'] : false;
                    $url = array_key_exists('url', $banner) ? $banner['url'] : null;
                    $target = array_key_exists('target', $banner) ? $banner['target'] : '_blank';
                    $bannerType = array_key_exists('banner_type', $banner) ? $banner['banner_type'] : '';
                    $image = array_key_exists('image', $banner) ? $banner['image'] : '';
                    $imageMobile = $banner['image_mobile'] ?? '';
                    $layout = $banner['layout'] ?? ''; // 0 - left, 1 - center, 2 - right
                    $altText = array_key_exists('alt_text', $banner) ? $banner['alt_text'] : '';
                    $video = array_key_exists('video', $banner) ? $banner['video'] : '';
                    $custom = array_key_exists('custom', $banner) ? $banner['custom'] : '';
                    $buttonText = array_key_exists('button_text', $banner) ? $banner['button_text'] : null;
                    $customContent = array_key_exists('custom_content', $banner) ? $banner['custom_content'] : '';
                ?>
                    <div id="banner-<?php echo $banner['id']; ?>" class="banner">
                        <?php if ($bannerType == 1) : ?>
                            <?php if (!$buttonText): ?>
                                <?php if (isset($url)): ?>
                                <a href="<?php echo $url; ?>" target="<?php echo $target; ?>" >
                                <?php endif; ?>
                            <?php endif; ?>
                                <div class="banner__image">
                                    <picture>
                                        <source media="(min-width: 768px)" srcset="<?php echo $mediaUrl . $image; ?>" />
                                        <source media="(max-width: 767px)" srcset="<?php echo $mediaUrl . $imageMobile; ?>" />
                                        <img src="<?php echo $mediaUrl . $image; ?>"
                                             alt="<?php echo $altText; ?>"
                                             title="<?php echo $altText; ?>"
                                            />
                                    </picture>
                                </div>
                            <?php if (!$buttonText): ?>
                                <?php if (isset($url)): ?>
                                </a>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php elseif ($bannerType == 3) : ?>
                            <?php if (!$buttonText): ?>
                                <?php if ($url): ?>
                                    <a href="<?php echo $url; ?>" target="<?php echo $target; ?>" >
                                <?php endif; ?>
                            <?php endif; ?>
                                <span class="banner-custom">
                                    <?php echo $custom; ?>
                                </span>
                            <?php if (!$buttonText): ?>
                                <?php if ($url): ?>
                                    </a>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php elseif ($bannerType == 2) : ?>
                            <span class="banner-video">
                                <?php echo $video; ?>
                            </span>
                        <?php endif; ?>
                        <?php if($layout == 0) {
                                $align = 'left';
                            } elseif ($layout == 1) {
                                $align = 'center';
                            } else {
                                $align = 'right';
                            }
                        ?>
                        <div class="banner__content align-<?php echo $align; ?>">
                            <?php if ($showTitle && $title) : ?>
                                <h2 class="banner__title"><?php echo $title; ?></h2>
                            <?php endif; ?>

                            <?php if ($showDescription && $description) : ?>
                                <p class="banner__description"><?php echo $description; ?></p>
                            <?php endif; ?>

                            <div class="banner__button">
                                <?php if ($buttonText && $url): ?>
                                    <a class="action button" href="<?php echo $url; ?>" target="<?php echo $target; ?>"> <?php echo $buttonText; ?> </a>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if ($customContent): ?>
                            <div class="clearfix"></div>
                            <div class="custom_content">
                                <?php echo $customContent; ?>
                            </div>
                        <?php endif; ?>
                    </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
