<?php /* @var \WeltPixel\OwlCarouselSlider\Block\Slider\Products $this */ ?>

<?php $sliderData    = $this->getSliderConfiguration(); ?>
<?php $enabled       = array_key_exists('status', $sliderData) ? $sliderData['status'] : ''; ?>
<?php $showPrice     = array_key_exists('show_price', $sliderData) ? $sliderData['show_price'] : false; ?>
<?php $showAddToCart = array_key_exists('show_addto', $sliderData) ? $sliderData['show_addto'] : false; ?>
<?php $showWishlist  = (array_key_exists('show_wishlist', $sliderData) && $sliderData['show_wishlist'] !=0) ? true : false; ?>
<?php $showCompare   = (array_key_exists('show_compare', $sliderData) && $sliderData['show_compare'] !=0) ? true : false; ?>
<?php if(!$enabled){ return; } ?>

<?php
$products = $this->getProductCollection();

if(!count($products)) { return; }

$productsType = $this->getData('products_type');
$sliderConfig = json_encode($sliderData);
$sliderTitle  = array_key_exists('title', $sliderData) ? $sliderData['title'] : '';
$breakpoint   = $this->getBreakpointConfiguration();
$breakpointConfig = json_encode($breakpoint);
$sliderType = 'widget-product-slider';

?>

<div class="product-slider">
    <div class="content-heading">
        <h2 class="title"><?php echo $sliderTitle; ?></h2>
    </div>
    <div class="<?php echo $sliderType;?> slider-hide"
        data-mage-init='{"rwSlider" : {
            "total": "<?php echo count($products) ?>",
            "sliderConfig": <?php echo $sliderConfig ?>,
            "breakpoints": <?php echo $breakpointConfig ?>
        }}'>
        <?php foreach($products as $product) : ?>

            <?php
            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
            $productImage = $_imagehelper->init($product, 'category_page_list')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(400)->getUrl();
            $productUrl   =  $product->getUrlModel()->getUrl($product);
            ?>

            <div class="item product product-item">
                <div data-container="product-grid" class="product-item-info">
                    <a tabindex="-1" class="product photo product-item-photo" href="<?php echo $productUrl; ?>">
                        <span style="width:240px;" class="product-image-container">
                            <span style="padding-bottom: 125%;" class="product-image-wrapper">
                                <img width="240" height="300" alt="<?php echo $product->getName(); ?>" data-src="<?php echo $productImage; ?>" class="product-image-photo lazyload"
                                    <?php echo $sliderData['lazyLoad'] ? 'data-src="' . $productImage . '" data-src-retina="' . $productImage . '" class="owl-lazy"' : '' ?>
                                />
                            </span>
                        </span>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a href="<?php echo $productUrl; ?>" class="product-item-link">
                                <?php echo $product->getName(); ?>
                            </a>
                        </strong>
                        <?php if($showPrice) : ?>
                            <?php /* @escapeNotVerified */ echo $this->getProductPrice($product); ?>
                        <?php endif; ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">

                                <?php if($showAddToCart) : ?>
                                    <div class="actions-primary">
                                            <?php if ($product->isSaleable()): ?>
                                                <?php if ($product->getTypeInstance()->hasRequiredOptions($product)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($product) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('View More') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('View More') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                    </div>
                                <?php endif; ?>

                                <div class="actions-secondary" data-role="add-to-links">
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">

                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($product); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>

                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php
                                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product);?>'
                                                   data-role="add-to-links"
                                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>