<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<div class="actions dropdown account-dropdown">
    <span class="action"
          data-mage-init='{"dropdown":{}}'
          data-toggle="dropdown"
          aria-haspopup="false"
          data-bind="text: '<?php echo __('Account');?>'">
    </span>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
    </script>
    <ul class="dropdown" data-bind="scope: 'customer'">
        <?php echo $block->getChildHtml('authorization-link');?>
        <?php echo $block->getChildHtml('register-link');?>
        <?php echo $block->getChildHtml('my-account-link');?>
        <?php echo $block->getChildHtml('wish-list-link');?>
        <?php echo $block->getChildHtml('multiple-wish-list-link');?>

        <!-- ko if: customer().fullname  -->
        <hr>
        <!-- /ko -->

    </ul>
</div>